const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("signalasi", {
  startBackend: () => ipcRenderer.invoke("backend:start"),
  backendStatus: () => ipcRenderer.invoke("backend:status"),
  getRuntimeDiagnostics: () => ipcRenderer.invoke("runtime:diagnostics"),
  getPairingStatus: () => ipcRenderer.invoke("pairing:status"),
  getPairingQr: () => ipcRenderer.invoke("pairing:qr"),
  clearPairing: (clientRouteId = "") => ipcRenderer.invoke("pairing:clear", clientRouteId),
  detectAgents: () => ipcRenderer.invoke("agents:detect"),
  getAgentDiagnostics: () => ipcRenderer.invoke("agents:diagnostics"),
  getAgentExecutionLog: (limit) => ipcRenderer.invoke("agents:execution-log", limit),
  getAgentTasks: (limit) => ipcRenderer.invoke("agents:tasks", limit),
  runAgentSelfTest: (options) => ipcRenderer.invoke("agents:self-test", options),
  getAgentConfig: () => ipcRenderer.invoke("agents:config:get"),
  saveAgentConfig: (config) => ipcRenderer.invoke("agents:config:save", config),
  testAgent: (agentId, prompt) => ipcRenderer.invoke("agents:test", agentId, prompt),
  sendMobileTest: (contactId, content) => ipcRenderer.invoke("mobile:test-message", contactId, content),
  syncMobileStatus: () => ipcRenderer.invoke("mobile:sync-status"),
  listDesktopTasks: (limit) => ipcRenderer.invoke("desktop-tasks:list", limit),
  getDesktopTask: (taskId) => ipcRenderer.invoke("desktop-tasks:get", taskId),
  startDesktopTask: (payload) => ipcRenderer.invoke("desktop-tasks:start", payload),
  cancelDesktopTask: (taskId) => ipcRenderer.invoke("desktop-tasks:cancel", taskId),
  retryDesktopTask: (taskId) => ipcRenderer.invoke("desktop-tasks:retry", taskId),
  deleteDesktopConversation: (conversationId) => ipcRenderer.invoke("desktop-conversations:delete", conversationId),
  getDesktopTools: () => ipcRenderer.invoke("desktop-tools:list"),
  invokeDesktopTool: (payload) => ipcRenderer.invoke("desktop-tools:invoke", payload),
  getDesktopControl: () => ipcRenderer.invoke("desktop-control:get"),
  updateDesktopControl: (settings) => ipcRenderer.invoke("desktop-control:update", settings),
  desktopControlAuthorizationAction: (authorizationId, action) =>
    ipcRenderer.invoke("desktop-control:authorization", authorizationId, action),
  getDesktopMemory: (query, limit) => ipcRenderer.invoke("desktop-memory:list", query, limit),
  rememberDesktopMemory: (payload) => ipcRenderer.invoke("desktop-memory:remember", payload),
  forgetDesktopMemory: (memoryId) => ipcRenderer.invoke("desktop-memory:forget", memoryId),
  getDesktopSkills: () => ipcRenderer.invoke("desktop-skills:list"),
  saveDesktopSkill: (payload) => ipcRenderer.invoke("desktop-skills:save", payload),
  setDesktopSkillEnabled: (skillId, enabled) => ipcRenderer.invoke("desktop-skills:enabled", skillId, enabled),
  deleteDesktopSkill: (skillId) => ipcRenderer.invoke("desktop-skills:delete", skillId),
  getDesktopMcp: () => ipcRenderer.invoke("desktop-mcp:list"),
  saveDesktopMcp: (payload) => ipcRenderer.invoke("desktop-mcp:save", payload),
  probeDesktopMcp: (connectionId) => ipcRenderer.invoke("desktop-mcp:probe", connectionId),
  deleteDesktopMcp: (connectionId) => ipcRenderer.invoke("desktop-mcp:delete", connectionId),
  chooseAttachments: () => ipcRenderer.invoke("files:choose"),
  openTaskArtifact: (taskId, relativePath) => ipcRenderer.invoke("task-artifact:open", taskId, relativePath),
  revealTaskWorkspace: (taskId) => ipcRenderer.invoke("task-workspace:reveal", taskId),
  loadLocale: (language) => ipcRenderer.invoke("i18n:load", language),
  pairingUrl: () => ipcRenderer.invoke("pairing:url"),
  openExternal: (url) => ipcRenderer.invoke("open:external", url),
  copyText: (text) => ipcRenderer.invoke("clipboard:write", text)
});
